---
title: "DataVisFinal"
author: "Sierra Cheung"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
library(dbplyr)
library(dplyr)
library(DT)
library(forcats)
library(geojsonsf)
library(geometries)
library(geospatial)
library(ggmap)
library(ggplot2)
library(leaflet)
library(RColorBrewer)
library(rgdal)
library(sp)
library(stringr)

# Let's install the development version from Github. Run
devtools::install_github("rstudio/leaflet")
```

```{r}
#load data
setwd('/Users/scheung/Desktop/Group_J_Climate_Economics')
finaldata <- read.csv('final_to_use.csv')
```
```{r}
#data wrangling
data2015 <- filter(finaldata, Year == 2015)
dataco2 <- filter(finaldata, is.na('co2_emission') == FALSE)
dataco2 <- filter(dataco2, Year > 2009)
dataco2 <- filter(dataco2, Year < 2016)
```

```{r}
country_count <- unique(dataco2['Country'])

for (i in 1:nrow(country_count)){
  country <- filter(dataco2, Country == country_count[i, 1])
  country_co2 <- country['co2_emission']
  country_co2 <- na.omit(country_co2)
  length_co2 <- nrow(country_co2)
  country_arableland <- country['Arable.Land']
  country_arableland <- na.omit(country_arableland)
  length_al <- nrow(country_arableland)
  country_count[i, 'avg_co2'] <- mean(country_co2[1:length_co2,'co2_emission'])
  country_count[i, 'arableland'] <- mean(country_arableland[1:length_al,'Arable.Land'])
}
country_count <- country_count[order(country_count$avg_co2, decreasing = TRUE, na.last = TRUE),]
top10co2 <- country_count[1:10,]
```

```{r}
plot1 <- ggplot(top10co2, aes(fill = Country, x= avg_co2, y= arableland, 
                              color = Country)) + 
  geom_point(position="dodge", stat="identity", width = 1, alpha = 0.7, size = 4) +
  xlab('CO2 Emissions') + ylab('Arable Land') + ggtitle("Average Arable Land and CO2
                                                        Emissions from 2010-2020")
plot1
```
##Plot #2
Co2 emissions +  life expectancy for countries worldwide (on a map)

```{r}
year2015 <- filter(dataco2, Year == 2015)
```

```{r}
#adding life expectancy to the plot data
for (i in 1:nrow(country_count)){
  country_count[i, 'life_expectancy'] <- year2015[i, 'Life.Expectancy']
  country_count[i, 'gdp'] <- year2015[i, 'GDP']
}



#excluding NA values
country_count <- na.omit(country_count)
```

```{r}
#plotting life expectancy and co2 emissions

#building world map (DO I NEED TO ADD COORDINATES OR....??)
m <- leaflet(country_count) %>%
  addTiles()
m
```

```{r}
popup_content <- paste("CO2 Emissions:",country_count$avg_co2,"<br/>",
                 "2015 Life Expetancy:",
                 country_count$life_expectancy,"<br/>",
                 "2015 GDP:",country_count$gdp,"<br/>")

#pal = colorFactor("Set1", domain = top20$) <~~ not sure what to set this as
#color_avail = pal(top_expense_rated$top_what) <~~ not sure what to do for this
leaflet(country_count) %>%
  addTiles() %>%
  addCircles(lng = ~longitude, lat = ~latitude, color = color_avail, popup = popup_content)%>%
  addLegend(pal = pal, values = ~top_expense_rated$top_what, title = "Type")
```

## Plot #3
Co2 emissions + GDP (how top 10 and bottom 10 GDP countries compare in CO2 emissions from 2010-2015)

```{r}
#finding top 10
country_count <- country_count[order(country_count$avg_co2, decreasing = TRUE, na.last = TRUE),]
top10co2 <- country_count[1:10,]

#finding bottom 10
country_count <- country_count[order(country_count$avg_co2, decreasing = FALSE, na.last = TRUE),]
bottom10co2 <- country_count[1:10,]

#binding top and bottom 10 co2 level countries
top10_bottom10 <- rbind(top10co2, bottom10co2)
```

```{r}
```

```{r}
```

```{r}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
